### PR TITLE
Allow null param map

### PR DESCRIPTION
**Pull request by Dhivyaa21**
Issue #42

### CODE REVIEW

**Comment by Dhivyaa21** [comment]
@cdancy - Done with the changes. Please review

**Comment by cdancy** [comment]
@martinda actually, and prior to releasing, I wonder if we should also support an empty map here? On the face of things it seems weird to support a null map but not an empty one.

**Comment by martinda** [comment]
@cdancy Yeah... I missed that feature:

https://github.com/cdancy/jenkins-rest/blob/0cf25b7fdc67e92db4f0ceec76e472598a8e7b39/src/main/java/com/cdancy/jenkins/rest/binders/BindMapToForm.java#L43

@Dhivyaa21 do you mind sending another pull-request please?

**Comment by Dhivyaa21** [comment]
Sure. I can send another one.

**Pull request merged**
