### PR TITLE
#226 Add method to Jobs Api to return JsonObject representation of th…

### PR DESCRIPTION
**Pull request by tyge68**
…e testReport endpoint

Please do not create a Pull Request without first creating an ISSUE.
Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the Pull Request.

Explain the **details** for making this change: What existing problem does the Pull Request solve? Why is this feature beneficial?

**On adding new features/endpoints**

No more than 1 endpoint should be coded within a Pull Request. 
This alone requires enough code to review and adding more than 1 WILL result in your Pull Request either being ignored or rejected outright.

**On adding Mock and Integ Tests**

At _least_ 2 mock tests and 2 integ tests are required prior to merging. 
Each pair should should test what the success and failure of added change looks like.
More complicated additions will of course require more tests.

**On CI testing (currently using travis)**

Code will not be reviewed until CI passes.
Current CI does NOT exercise `integ` tests and so each Pull Request will have to be run manually by one of the maintainers to confirm it works as expected: please be patient.

**On automtatic closing of ISSUES**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by cdancy** [comment]
Looks good enough. @tyge68 a live test would be nice to confirm all works as expected. Also ... what happens if there is no "test report" returned?

@martinda any thoughts?

**Comment by martinda** [comment]
I agree, this is a nice feature. I just tried it on a localhost instance and it works. An integration test would be awesome, both for the case of no existing and existing test report. Do you think you can do that @tyge68 please?

**Comment by tyge68** [comment]
@martinda  I just added a new test for case with no testReport which basically returns null in that case.

Feel free to adjust etc.. based on your needs.

**Comment by tyge68** [comment]
@cdancy  thanks for the merge, do you have already some planned date for the next official release ?

**Pull request merged**
