### PR TITLE
add lastStableBuildTimestamp lastStableBuildNumber method 

### PR DESCRIPTION
**Pull request by hcray**
**On adding lastStableBuildTimestamp lastStableBuildNumber method 

**On adding lastStableBuildTimestamp lastStableBuildNumber Mock and Integ Tests**

### CODE REVIEW

**Comment by martinda** [comment]
Hello @hcray , thanks for this PR. I ran the live tests on my end and they pass. You may want to configure your email address in Git and/or register the one you use with github to get the credit.

This PR looks good to me.

**Comment by hcray** [comment]
@martinda I have updated public email address.

**Comment by martinda** [comment]
@hcray you need to rewrite the commits with your email address if you want them to show your github avatar.

**Comment by cdancy** [comment]
@hcray the live tests, while good, don't test when things are successful. @martinda has written some harnesses around how to do a fully live test with builds in some of out other integration tests. We would need those done first before accepting the PR. If you need help just scream in our direction.

**Comment by hcray** [comment]
@martinda my mistake, I have change my git config, next I will rewrite the commits history

**Comment by hcray** [comment]
rewrite the commits

**Pull request closed without merging**
