### PR TITLE
Pipeline REST API #60

### PR DESCRIPTION
**Pull request by choweiyuan**
Explain the **details** for making this change: What existing problem does the Pull Request solve? Why is this feature beneficial?
See #60

### CODE REVIEW

**Comment by choweiyuan** [comment]
Hi @cdancy  any updates on this?

**Comment by cdancy** [comment]
@choweiyuan apologies for not getting back to this. Saw it a while ago and it slipped my mind. Looking over things now...

**Comment by cdancy** [comment]
@choweiyuan is it possible to add live/integ tests?

**Comment by cdancy** [comment]
LGTM. Thanks for the PR!

**Comment by choweiyuan** [comment]
Sorry just saw this . 
1. Do you still want me to add the relevant tests or am I okay to close the issue?
2. When will you do a release with this feature? :) Thanks

**Comment by cdancy** [comment]
@choweiyuan no worries. Things worked for me in some simple tests but still would like to have some live tests at some point. I assume you'd like a new release kicked with these changes?

**Comment by cdancy** [comment]
New release has just been kicked with this change.

**Comment by choweiyuan** [comment]
thank you!

**Pull request merged**
